name: ecotrack_lite
description: A new Flutter project with authentication features.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.1
  email_validator: ^3.0.0

  # Networking & HTTP requests
  http: ^1.1.0
  dio: ^5.3.3

  # Data Persistence & Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # Internationalization
  intl: ^0.19.0

  # Utilities & Misc
  url_launcher: ^6.2.2
  package_info_plus: ^8.1.0
  form_validator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - images/google_logo.png
    - images/logo-white.png
  